name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: japri-test # TODO: update Google Cloud project id
  SERVICE: sayhello-github # TODO: update Cloud Run service name
  REGION: asia-southeast1 # TODO: update Cloud Run service region

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SA_CREDS }}'

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy $SERVICE \
            --project $PROJECT_ID \
            --region $REGION \
            --source ./ \
            --allow-unauthenticated
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
